### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by bruno-garcia** [alesdvorakcz/sentry-test#1]
Your `Program.cs` can be simplified by:

From:
```csharp
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .ConfigureAppConfiguration((context, builder) =>
        {
            builder
                .SetBasePath(context.HostingEnvironment.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{context.HostingEnvironment.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();
        })
        .ConfigureServices(services =>
        {
            services.AddSingleton<IStartup, Startup>();
        })
        .UseSentry();
```
To:
```csharp
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()
        .UseSentry();
```

That is because the `CreateDefaultBuilder` already sets up the configuration lookign for `appsettings.json` and `appsettings.ENV.json`. And `UseStartup` is a shorthand to registering `IStartup` as you did through `ConfigureServices`.

Also, there's no need to have a base controller with a try catch and have every action of yours go through that.

If your controller throughs an unhandled exception, Sentry will automatically capture while sending data related to the request to help you debug.

I suggest taking a look at this sample: https://github.com/getsentry/sentry-dotnet/tree/master/samples/Sentry.Samples.AspNetCore.Mvc

**Comment by alesdvorakcz** [comment]
Thanks. its a copy paste from older project with .net core 1.0 where it was no easy like that.

Base Controller is not used only for logging exceptions but also for returning correct http status and body for different exception types. Maybe it would be better to have some mvc action filter for that

**Comment by bruno-garcia** [comment]
I would suggest using a Middleware in that case.
An unhandled exception will return status code 500 OOTB though.
